---
- hosts: localhost
  connection: local
  tasks:
    - name: Create the AWS VPC
      amazon.aws.ec2_vpc_net:
        name: myvpcinkatha_auto
        cidr_block: 10.100.0.0/16
        region: us-east-1
        state: absent
      register: aws_vpc_info

    - name: create subnet  1
      amazon.aws.ec2_vpc_subnet:
        #state: present
        state: absent
        vpc_id: "{{ aws_vpc_info.vpc.id}}"
        region: us-east-1
        cidr: 10.100.0.0/24
        tags:
          Name: public-subnet
      register: public_subnet_info  

    - name: create subnet 2 
      amazon.aws.ec2_vpc_subnet:
        #state: present
        state: absent
        vpc_id: "{{ aws_vpc_info.vpc.id}}"
        region: us-east-1
        cidr: 10.100.1.0/24
        tags:
          Name: private-subnet
      register: private_subnet_info    

    - name: Create Internet Gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ aws_vpc_info.vpc.id}}"
        tags:
          Name: internet-gateway-2nd
        state: absent
      register: internet_gateway_info

    - name: set up route table
      amazon.aws.ec2_vpc_route_table:
        subnets:
          - "{{ public_subnet_info.subnet.id}}"
          - "{{ private_subnet_info.subnet.id}}"
        vpc_id: "{{ aws_vpc_info.vpc.id }}"
        state: absent
      register: vpc_route_table

    - name:  create a new nat gateway private
      amazon.aws.ec2_vpc_nat_gateway:
       #
        subnet_id: "{{ private_subnet_info.subnet.id}}"
        wait: true
        region: us-east-1
        state: absent
      register: new_nat_gateway_private  
    

    - name:  create security groups
      amazon.aws.ec2_security_group:
        name: first-vpc-security-group
        state: absent
        description: vpc security group
        vpc_id: "{{ aws_vpc_info.vpc.id }}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/8
          - proto: tcp
            from_port: 443
            to_port: 443  
            cidr_ip: 0.0.0.0/0
    
          


