---
- hosts: localhost
  connection: local
  tasks:
    - name: Create the AWS VPC
      amazon.aws.ec2_vpc_net:
        name: myvpcinkatha_auto
        cidr_block: 10.100.0.0/16
        region: us-east-1
      register: aws_vpc_info
    - name: Make sure subnet exists  
      amazon.aws.ec2_vpc_subnet:
        state: present
        vpc_id: "{{ aws_vpc_info.vpc.id}}"
        region: us-east-1
        cidr: 10.100.0.0/24
        tags:
          Name: first-vpc-subnet
    - name: Create Internet Gateway
      amazon.aws.ec2_ vpc_igw:
        vpc_id: "{{ aws_vpc_info.vpc.id}}"
        tags:
          Name: internet-gateway-2nd
        state: present
      register: internet-gateway  

    - name: set up route table
      amazon.aws.ec2_vpc_route_table:
        subnets:
          - "{{ aws}}"
        vpc_id: "{{ aws_vpc_info.vpc.id }}"
        register: vpc_route_table

    - name:  create a new nat gateway
      amazon.aws.ec2_vpc_nat_gateway:
        state:  present
        #subnet_id: {{ first-vpc-subnet.vpc}}
        wait: true
        region: "{{ aws_vpc_info.}}"
      register: new_nat_gateway  

    - name:  create security groups
      amazon.aws.ec2_security_group:
        Name:
        description:
        vpc_id:
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/8
          - proto: tcp
            from_port: 443
            to_port: 443  


