---
- hosts: localhost
  connection: local
  vars:
     vpc_name: "{{ prefix }}vpc"
     region: us-east-1
     az0: "us-east-1a"
     az1: "us-east-1b"
     prefix: "stagingNKathad"
     igw_name: "multi-az-vpc"
     route_table_name: "{{ prefix }}Route Table"
     security_group_name: "{{ prefix}}Security Group"
  tasks:
    - name: Create the AWS VPC
      amazon.aws.ec2_vpc_net:
        name: "stagingNKathadvpc"
        cidr_block: 10.0.0.0/16
        region: us-east-1
        state: present
      register: aws_vpc_info
     

    - name: create public subnet 1
      amazon.aws.ec2_vpc_subnet:
        state: present
        vpc_id: "{{ aws_vpc_info.vpc.id}}"
        region: "{{ region }}"
        az: "{{ az0 }}"
        map_public: yes
        cidr: 10.0.0.0/24
        resource_tags: '{"Name":"{{ prefix }}_subnet_public_0"}'
      register: subnet_result0 

    - name: create public subnet 2
      amazon.aws.ec2_vpc_subnet:
        state: present
        vpc_id: "{{ aws_vpc_info.vpc.id}}"
        region: "{{ region }}"
        az: "{{ az1}}"
        map_public: yes
        cidr: 10.0.1.0/24
        resource_tags: '{"Name":"{{ prefix }}_subnet_public_1"}'
      register: subnet_result1  

    - name: create private subnet 1
      amazon.aws.ec2_vpc_subnet:
        state: present
        vpc_id: "{{ aws_vpc_info.vpc.id}}"
        region: "{{ region }}"
        az: "{{ az0}}"
        cidr: 10.0.2.0/24
        resource_tags: '{"Name":"{{ prefix }}_subnet_private_0"}'
      register: subnet_result2

    - name: create private subnet 2
      amazon.aws.ec2_vpc_subnet:
        state: present
        vpc_id: "{{ aws_vpc_info.vpc.id}}"
        region: "{{ region }}"
        az: "{{ az1}}"
        cidr: 10.0.3.0/24
        resource_tags:
          Name: "{{ prefix }}_subnet_private_1"
      register: subnet_result3  

    - name: Create Internet Gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ aws_vpc_info.vpc.id}}"
        tags:
          Name: "{{ igw_name}}"
        state: present
      register: internet_gateway_result

    - name: set up route table
      amazon.aws.ec2_vpc_route_table:
        tags:
          Name: "{{ route_table_name }}"
        subnets:
          - "{{ subnet_result0.subnet.id }}"
          - "{{ subnet_result1.subnet.id }}"
       
        vpc_id: "{{ aws_vpc_info.vpc.id }}"
      register: vpc_route_table


    

    - name:  create security groups
      amazon.aws.ec2_security_group:
        name: "{{ security_group_name }}"
        description: vpc security group
        vpc_id: "{{ aws_vpc_info.vpc.id }}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/8
          - proto: tcp
            from_port: 443
            to_port: 443  
            cidr_ip: 0.0.0.0/0
    
    - name:  create a new nat gateway private
      amazon.aws.ec2_vpc_nat_gateway:
        state:  present
        subnet_id: 
          - "{{ subnet_result2.subnet.id }}"
          - "{{ subnet_result3.subnet.id }}" 
        wait: true
        region: "{{ region }}"
      register: new_nat_gateway_private         


